config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  root "pages#home"
  resource :subcribers
  resources :products, only: [:show, :index] do
    member do
      get :order
      post :send_order
    end
  end
  resources :blogs, only: [:show, :index]
  resources :medias, only: [:show, :index]
  resources :contacts, only: [:index, :create]
  get "/products" => "products#index", as: :search_product

  namespace :admin do
    root "home#show"
    resources :home, only: [:show]
    resources :fields
    resources :brands
    resource :company, only: [:show, :update, :edit]
    resources :sliders
    resources :catalogs
    resources :products
    resources :categories
    resources :imports
    resources :tags
    resources :subscribers
    get "/edit_company" => "companies#edit", as: :edit_company
    resources :fields
    resources :medias
    devise_for :admins, :controllers => {:sessions => 'admin/sessions',
      :passwords => 'admin/passwords' }, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
    resources :blogs
    post "/templates/:id" => "templates#show", defaults: {format: "json"}, as: :template
    resources :templates, only: [:index, :create, :update, :destroy]
  end
end

app/views/layouts/admin/_top_left_layout.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
    <%= link_to "Admin", admin_root_url, class: "navbar-brand"%>
  </div>
  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li><a href="#"><i class="fa fa-user fa-fw"></i> Tài khoản</a>
        </li>
        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Cài đặt</a>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to destroy_admin_admin_session_path(), :method => :delete do %>
            <i class="fa fa-sign-out fa-fw"></i>Đăng xuất
          <% end %>
        </li>
        </li>
      </ul>
    </li>
  </ul>

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li>
          <%= link_to admin_company_path() do %>
            <i class="fa fa-dashboard fa-fw"></i>
            Công ty
          <% end %>
        </li>

        <li>
          <%= link_to admin_subscribers_path() do %>
            <i class="fa fa-dashboard fa-fw"></i>
            Khách hàng
          <% end %>
        </li>

        <li>
          <a href="#">
            <i class="fa fa-table fa-fw"></i> Danh mục
            <span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to "Tất cả danh mục", admin_categories_path() %>
            </li>
            <li>
              <%= link_to "Danh mục trên trang chủ", admin_root_url() %>
            </li>
          </ul>
        </li>

        <li>
          <a href="#">
            <i class="fa fa-bar-chart-o fa-fw"></i> Sản phẩm
            <span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to "Danh sách sản phẩm", admin_products_path() %>
            </li>
            <li>
              <%= link_to "Import - Export", new_admin_import_path() %>
            </li>
          </ul>
        </li>

        <li>
          <%= link_to admin_fields_path() do %>
            <i class="fa fa-edit fa-fw"></i>
            Lĩnh vực
          <% end %>
        </li>

        <li>
          <%= link_to admin_brands_path() do %>
            <i class="fa fa-wrench fa-fw"></i>
            Hãng sản xuất
          <% end %>
        </li>

        <li>
          <%= link_to admin_tags_path() do %>
            <i class="fa fa-wrench fa-fw"></i>
            Tag
          <% end %>
        </li>

        <li>
          <a href="#">
            <i class="fa fa-sitemap fa-fw"></i> Slider + Catalog
            <span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to "Slider", admin_sliders_path() %>
            </li>
            <li>
              <%= link_to "Catalog", admin_catalogs_path() %>
            </li>
          </ul>
        </li>

        <li>
          <a href="#">
            <i class="fa fa-bar-chart-o fa-fw"></i> Bài viết
            <span class="fa arrow"></span>
          </a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to "Quản lý bài viết", admin_blogs_path %>
            </li>
            <li>
              <%= link_to "Quản lý template bài viết", admin_templates_path %>
            </li>
          </ul>
        </li>

        <li>
          <%= link_to admin_medias_url(media_type: "0") do %>
            <i class="fa fa-files-o fa-fw"></i>
            Tài liệu
          <% end %>
        </li>

        <li>
          <%= link_to admin_medias_url(media_type: "1") do %>
            <i class="fa fa-files-o fa-fw"></i>
            Video
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html lang="en-US">

<head>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Admin</title>
</head>

<body>
  <div id="wrapper">
    <% if admin_admin_signed_in? %>
      <%= render "layouts/admin/top_left_layout" %>
    <% end %>
    <%= yield %>
  </div>
</body>

</html>