config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  root "pages#home"
  resource :subcribers
  resources :products, only: [:show, :index] do
    member do
      get :order
      post :send_order
    end
  end
  resources :blogs, only: [:show, :index]
  resources :medias, only: [:show, :index]
  resources :contacts, only: [:index, :create]
  get "/products" => "products#index", as: :search_product

  namespace :admin do
    root "home#show"
    resources :home, only: [:show]
    resources :fields
    resources :brands
    resource :company, only: [:show, :update, :edit]
    resources :sliders
    resources :catalogs
    resources :products
    resources :categories
    resources :imports
    resources :tags
    resources :subscribers
    get "/edit_company" => "companies#edit", as: :edit_company
    resources :fields
    resources :medias
    devise_for :admins, :controllers => {:sessions => 'admin/sessions',
      :passwords => 'admin/passwords' }, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
    resources :blogs
    post "/templates/:id" => "templates#show", defaults: {format: "json"}, as: :template
    resources :templates, only: [:index, :create, :update, :destroy]
  end
end

app/controllers/admin/medias_controller.rb
class Admin::MediasController < Admin::BaseController

  before_action :load_doc, only: [:edit, :update]

  def index
    filter_media_param = params[:filter_video_field] || params[:filter_doc_field]
    if filter_media_param.present?
      @medias = Medium.where("media_type = ? AND field_id = ?", params[:media_type], filter_media_param)
    else
      @medias = Medium.where("media_type = ?", params[:media_type])
    end
    @video = Medium.new(media_type: "1")
  end

  def new
    @doc = Medium.new(media_type: "0")
  end

  def create
    if params[:medium][:media_type] == "0"
      @doc = Medium.new(media_params)
      if @doc.save
        flash[:success] = "Tạo mới Tài liệu #{@doc.title} thành công"
        redirect_to admin_medias_path(media_type: "0")
      else
        flash[:danger] = "Lỗi! Tạo mới Tài liệu không thành công"
        render :new
      end
    else
      @video = Medium.new(media_params)
      if @video.save
        flash[:success] = "Tạo mới video #{@video.title} thành công"
        redirect_to admin_medias_path(media_type: "1")
      else
        flash[:danger] = "Lỗi! Tạo mới video không thành công"
      end   
    end
  end

  def edit
  end

  def update
    if params[:title] || params[:video_url] || params[:description] || params[:field_id]
      @video = Medium.find_by id: params[:id]
      if @video
        if @video.update_attributes(title: params[:title], field_id: params[:field_id],
          video_url: params[:video_url], description: params[:description])
          render json: {
            status: "update-success",
            title: @video.title,
            description: @video.description,
            video_url: @video.video_url
          }
        else
          render json: {status: "update-fail"}
        end
      end
    end

    if @doc.update_attributes(media_params)
      flash[:success] = "Chỉnh sửa thàng công"
      redirect_to admin_medias_path(media_type: "0")
    end
  end

  def destroy
    if params[:media_type] == "1"
      @video = Medium.find_by id: params[:id]
      if @video
        if @video.destroy
          flash[:success] = "Xoá video #{@video.title} thành công!"
        else
          flash[:danger] = "Lỗi! Xóa video không thành công."
        end
        redirect_to admin_medias_path(media_type: "1")
      end
    else
      @doc = Medium.find_by id: params[:id]
      if @doc
        if @doc.destroy
          flash[:success] = "Xoá Tài liệu #{@doc.title} thành công!"
        else
          flash[:danger] = "Lỗi! Xóa Tài liệu không thành công."
        end
        redirect_to admin_medias_path(media_type: "0")
      end  
    end
  end

  private
  def load_doc
    @doc = Medium.find params[:id]
  end

  def media_params
    params.require(:medium).permit Medium::MEDIA_ATTRIBUTE
  end
end

app/controllers/medias_controller.rb
class MediasController < ApplicationController
  before_action :load_breadcrum, only: :index

  def index
    if params[:media_type] == "0"
      per_page_medias = Settings.limit.paginate.documents
    else
      per_page_medias = Settings.limit.paginate.videos
    end

    if params[:query].present?
      @media_ids = Medium.search(body: {query: {bool: {must: [{match: {_all: params[:query]}}, {match: {media_type: params[:media_type].to_i}}]}}})
        .map(&:id)
      unless @media_ids.present?
        @medias = []
        return
      end
    end

    @medias = if @media_ids.present?
      Medium.where id: @media_ids
    else
      Medium.all
    end

    @medias = if params[:field_id].present?
      @medias.where("media_type = ? AND field_id = ?", params[:media_type], params[:field_id])
        .page(params[:page]).per(per_page_medias)
    else
      @medias.where("media_type = ?", params[:media_type])
        .page(params[:page]).per(per_page_medias)
    end
  end

  private
  def load_breadcrum
    if params[:media_type] == "0"
      @breads = [{title: "Tài liệu", link: ""}]
    elsif params[:media_type] == "1"
      @breads = [{title: "Video", link: ""}]
    end
  end
end

app/views/admin/medias/_doccument.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Tài liệu</h1>
    </div>
  </div>

  <div class="row" id="doc-table">
    <div class="col-lg-12">
      <div class="create-div">
        <%= link_to "Tạo mới", new_admin_media_path, class: "btn btn-success" %>
      </div>
      <br>
      <div style="width: 30%">Lọc theo lĩnh vực:
        <%= form_tag({}, {:method => :get}) do %>
          <%= select_tag "filter_doc_field", options_for_select(Field.all.map{|field| [field.name, field.id]}, selected: params[:filter_doc_field]),
            include_blank: "--Chọn một lĩnh vực--", :onchange => "this.form.submit();", class: "form-control" %>
          <input type="hidden" name="media_type" value="0">
        <% end %>
      </div>
      <br>

      <%= render "shared/flash" %>
      
      <!-- content -->      
      <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-doc">
          <thead>
            <tr>
              <th>Id</th>
              <th>Tài liệu</th>
              <th>Title</th>
              <th>Mô tả</th>
              <th>Lĩnh vực</th>
              <th class="center"></th>
              <th class="center"></th>
            </tr>
          </thead>
          <tbody>
            <% @medias.each do |doc| %>
              <tr>
                <td><%= doc.id %></td>
                <td>
                  <a href="<%= doc.url %>">
                    <% if doc.document_type == "pdf" %>
                      <%= image_tag "/small-pdf.png", title: "pdf" %>
                    <% elsif doc.document_type == "doc" || doc.document_type == "ocx" %>
                      <%= image_tag "/small-word.png", title: "doc" %>
                    <% elsif doc.document_type == "xls" || doc.document_type == "lsx" %>
                      <%= image_tag "/small-excell.png", title: "excel" %>
                    <% end %>
                    <%= doc.url.current_path.split("/").last if doc.url.current_path %>
                  </a>
                </td>
                <td><%= doc.title %></td>
                <td><%= doc.description %></td>
                <td>
                  <%= doc.field.name %>
                </td>
                <td class="center">
                  <%= link_to "Chỉnh sửa", edit_admin_media_path(doc, media_type: "0"), class: "btn btn-primary"%>
                </td>
                <td class="center">
                  <%= link_to "Xóa", admin_media_path(doc, media_type: "0"), method: :delete, data: {confirm: "Bạn có chắc chắn xóa"},class: "btn btn-danger" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- end content -->
    </div>
  </div>
</div>

app/views/admin/medias/_modal_video.html.erb
<div class="modal fade" id="create-video" tabindex="-1" role="dialog" aria-labelledby="create" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal" aria-label="close">&times;</a>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title custom_align" id="Heading">Tạo Video mới</h4>
      </div>
      <%= form_for @video, url: admin_medias_url do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.text_field :title, class: "form-control video-name-create", placeholder: "Tên Video", required: true, oninvalid: "Please Enter valid email" %>
          </div>
          <div class="form-group">
            <%= f.text_area :description, class: "form-control video-des-create", row: "2", placeholder: "Mô tả", required: true %>
          </div>
          <div class="form-group">
            <%= f.text_field :url, class: "form-control video-link-create", placeholder: "Youtube Link", required: true %>
          </div>
          <div class="form-group">
            <%= f.select :field_id, options_for_select(Field.all.map{|field| [field.name, field.id]}), {},
              {class: "video-field-create form-control"} %>
          </div>
          <%= f.hidden_field :media_type, value: "1" %>
        </div>
        <div class="modal-footer ">
          <button type="button" class="btn btn-default btn-lg" data-dismiss="modal">Bỏ qua</button>
          <%= f.submit "Tạo", class: "btn btn-success btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/medias/_video.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Videos</h1>
    </div>
  </div>

  <div class="row" id="video-table">
    <div class="col-lg-12">
      <div class="create-div">
        <button class="btn btn-success" data-title="Tạo mới" data-toggle="modal" data-target="#create-video" >
          Tạo mới
        </button>
      </div>
      <br>
      <div style="width: 30%">Lọc theo lĩnh vực:
        <%= form_tag({}, {:method => :get}) do %>
          <%= select_tag "filter_video_field", options_for_select(Field.all.map{|field| [field.name, field.id]}, selected: params[:filter_video_field]),
            include_blank: "--Chọn một lĩnh vực--", :onchange => "this.form.submit();", class: "form-control" %>
          <input type="hidden" name="media_type" value="1">
        <% end %>
      </div>
      <br>

      <%= render "shared/flash" %>
      
      <!--messages start -->

      <div class="alert alert-success video-alert-success-update hidden">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Thành công!</strong> Sửa thành công.
      </div>
      <div class="alert alert-danger video-alert-danger-update hidden">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Lỗi!</strong> Sửa không thành công.
      </div>

      <!-- messages end -->

      <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-video">
          <thead>
            <tr>
              <th>Id</th>
              <th>Tên video</th>
              <th>Mô tả</th>
              <th>Link Youtube</th>
              <th>Lĩnh vực</th>
              <th class="center"></th>
              <th class="center"></th>
            </tr>
          </thead>
          <tbody>
            <% @medias.each do |video| %>
              <tr class="odd gradeX" id="video<%= video.id %>">
                <td><%= video.id %></td>
                <td class="td-video-name">
                  <p class="p-video-name" id="p-video-name<%= video.id %>"><%= video.title %></p>
                  <input type='text' id="video-name<%= video.id %>" class="form-control video-name hidden" value='<%= video.title %>'/>
                </td>
                <td class="td-video-des">
                  <p class="p-video-des" id="p-video-des<%= video.id %>"><%= video.description %></p>
                  <textarea rows="2" id="video-des<%= video.id %>" class="form-control video-des hidden"><%= video.description %></textarea>
                </td>
                <td class="td-video-link">
                  <p class="p-video-link" id="p-video-link<%= video.id %>"><%= video.video_url %></p>
                  <input type='text' id="video-link<%= video.id %>" class="form-control video-link hidden" value='<%= video.video_url %>'/>
                </td>
                <td class="td-video-field">
                  <%= select_tag "video-field#{video.id}", options_for_select(Field.all.map{|field| [field.name, field.id]}, selected: video.field_id),
                    {class: "video-field-create form-control"} %>
                </td>
                <td class="center">
                  <button type="button" name="update-video<%= video.id %>" class="btn btn-primary confirm-video-save">Lưu</button>
                </td>
                <td class="center">
                  <p data-placement="top" data-toggle="tooltip" title="Xóa">
                    <button class="btn btn-danger button-delete-video" data-title="Xóa" data-toggle="modal" data-target="#delete" id="delete-video<%= video.id %>" >
                      Xóa
                    </button>
                  </p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="delete" aria-hidden="true">
    <input type="hidden" class="delete-video-id" value="Norway">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <a href="#" class="close" data-dismiss="modal" aria-label="close">&times;</a>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
          <h4 class="modal-title custom_align" id="Heading">Xóa Video</h4>
        </div>
        <div class="modal-body">
          <div class="alert alert-danger">Bạn có chắc chắn xóa Video <strong class="delete-video-name"></strong> không?</div>
        </div>
        <div class="modal-footer ">
          <button type="button" class="btn btn-success" id="button-delete-video-confirm" >Có</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Không</button>
        </div>
      </div>
    </div>
  </div>
  
  <%= render "modal_video" %>

</div>

app/views/admin/medias/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Tài liệu</h1>
    </div>
  </div>

  <div class="row" id="doc-table">
    <div class="col-lg-6">
      <%= form_for([:admin, @doc], url: { action: :update }, html: {multipart: true}) do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control doc-name-create", placeholder: "Tên doc", required: true, oninvalid: "Please Enter valid email" %>
        </div>

        <div class="form-group">
          <%= f.text_area :description, class: "form-control doc-des-create", rows: "4", placeholder: "Mô tả", required: true %>
        </div>
        <div class="form-group">
          <%= f.select :field_id, options_for_select(Field.all.map{|field| [field.name, field.id]}, selected: f.object.field_id), {},
            {class: "doc-field-create form-control"} %>
        </div>
        <div class="form-group">
          <%= f.file_field :url, class: "doc-link-create", placeholder: "Youtube Link", required: true, onchange: "validateFiles(this);",
            data: {max_file_size: 5.megabytes} %>
        </div>
        <%= f.hidden_field :media_type, value: "0" %>
        <div class="text-center">
          <%= link_to "Bỏ qua", admin_medias_path(media_type: "0"), class: "btn btn-default btn-lg" %>
          <%= f.submit "Sửa", class: "btn btn-success btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/medias/index.html.erb
<% if params[:media_type] == "0" %>
  <%= render partial: "doccument", object: @medias %>
<% else %>
  <%= render partial: "video", object: @medias %>
<% end %>

app/views/admin/medias/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Tài liệu</h1>
    </div>
  </div>

  <div class="row" id="doc-table">
    <div class="col-lg-6">
      <%= form_for([:admin, @doc], url: admin_medias_path, html: {multipart: true}) do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control doc-name-create", placeholder: "Tên doc", required: true, oninvalid: "Please Enter valid email" %>
        </div>

        <div class="form-group">
          <%= f.text_area :description, class: "form-control doc-des-create", rows: "4", placeholder: "Mô tả", required: true %>
        </div>
        <div class="form-group">
          <%= f.select :field_id, options_for_select(Field.all.map{|field| [field.name, field.id]}), {},
            {class: "doc-field-create form-control"} %>
        </div>
        <div class="form-group">
          <%= f.file_field :url, class: "doc-link-create", placeholder: "Youtube Link", required: true, onchange: "validateFiles(this);",
            data: {max_file_size: 5.megabytes} %>
        </div>
        <%= f.hidden_field :media_type, value: "0" %>
        <div class="text-center">
          <%= link_to "Bỏ qua", admin_medias_path(media_type: "0"), class: "btn btn-default btn-lg" %>
          <%= f.submit "Tạo", class: "btn btn-success btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>