config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  root "pages#home"
  resource :subcribers
  resources :products, only: [:show, :index] do
    member do
      get :order
      post :send_order
    end
  end
  resources :blogs, only: [:show, :index]
  resources :medias, only: [:show, :index]
  resources :contacts, only: [:index, :create]
  get "/products" => "products#index", as: :search_product

  namespace :admin do
    root "home#show"
    resources :home, only: [:show]
    resources :fields
    resources :brands
    resource :company, only: [:show, :update, :edit]
    resources :sliders
    resources :catalogs
    resources :products
    resources :categories
    resources :imports
    resources :tags
    resources :subscribers
    get "/edit_company" => "companies#edit", as: :edit_company
    resources :fields
    resources :medias
    devise_for :admins, :controllers => {:sessions => 'admin/sessions',
      :passwords => 'admin/passwords' }, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
    resources :blogs
    post "/templates/:id" => "templates#show", defaults: {format: "json"}, as: :template
    resources :templates, only: [:index, :create, :update, :destroy]
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :load_products, only: :index
  before_action :load_product, only: [:new, :create, :edit, :update, :destroy]

  def index
  end

  def new
    @product = Product.new
    @product.product_categories.build
    @product.product_images.build
    @product.product_images.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Tạo mới sản phẩm #{@product.name} thành công!"
      redirect_to admin_products_path
    else
      @category_attrs = category_params
      @field_attrs = field_params
      @video_attrs = media_params
      @document_attrs = media_params
      flash[:danger] = @product.errors.full_messages
      render :new
    end
  end

  def edit
    @category_attrs = category_params
    @field_attrs = field_params
    @video_attrs = media_params
    @document_attrs = media_params
    unless @product.product_images.present?
      @product.product_images.build
      @product.product_images.build
    end
  end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = "Sửa sản phẩm #{@product.name} thành công!"
      redirect_to admin_products_path
    else
      @category_attrs = category_params
      @field_attrs = field_params
      @video_attrs = media_params
      @document_attrs = media_params
      flash[:danger] = @product.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = "Xóa sản phẩm #{@product.name} thành công!"
    else
      flash[:danger] = "Lỗi! Xóa sản phẩm không thành công."
    end
    redirect_to admin_products_path()
  end
  private
  def product_params
    params.require(:product).permit(Product::PRODUCT_ATTRIBUTES,
      product_images_attributes: Product::PRODUCT_IMAGE_ATTRIBUTES,
      product_categories_attributes: Product::PRODUCT_CATEGORY_ATTRIBUTES,
      product_fields_attributes: Product::PRODUCT_FIELD_ATTRIBUTES,
      product_media_relations_attributes: Product::PRODUCT_MEDIA_ATTRIBUTES)
  end

  def load_products
    get_categories
    @products = get_products_by_categories
  end

  def load_product
    @product = Product.find_by id: params[:id]
    get_categories
    get_fields
    get_medias
  end

  def field_params
    arr = {}
    if @product.product_fields
      @product.product_fields.each do |field|
        arr[field.field_id.to_s] = field.list_order
      end
    else
      params[:product][:product_fields_attributes].each do |key, value|
        arr[value[:field_id]] = value[:list_order]
      end
    end
    arr
  end

  def media_params
    arr = {}
    if @product.product_media_relations
      @product.product_media_relations.each do |medium|
        arr[medium.medium_id.to_s] = medium.medium_id.to_s
      end
    else
      params[:product][:product_media_relations_attributes].each do |key, value|
        arr[value[:medium_id]] = value[:medium_id]
      end
    end
    arr
  end

  def category_params
    arr = {}
    if @product.product_categories
      @g_categories.each_with_index do |c, index|
        @product.product_categories.each do |pc|
          if c.all_children_ids.include? pc.category_id
            arr[index] = {category_id: pc.category_id, list_order: pc.list_order}
            break
          end
        end
      end
    else
      @g_categories.each_with_index do |c, index|
        params[:product][:product_categories_attributes].each do |key, value|
          if c.all_children_ids.include? value[:category_id].to_i
            arr[index] = {category_id: value[:category_id].to_i, list_order: value[:list_order]}
            break
          end
        end
      end
    end
    arr
  end

  def get_fields
    @fields = Field.all.order(menu_order: :asc)
  end

  def get_medias
    @videos = Medium.where(media_type: 1)
    @documents = Medium.where(media_type: 0)
  end

  def get_categories
    @g_categories = Category.where(level: Settings.category.highest_level)
    if params[:gc_id].present?
      g_category = Category.find_by id: params[:gc_id]
      @p_categories = g_category.childrens
    else
      params[:pc_id] = params[:c_id] = nil
    end

    if params[:pc_id].present? && @p_categories.pluck(:id).include?(params[:pc_id].to_i)
      p_category = Category.find_by id: params[:pc_id]
      @categories = p_category.childrens
    else
      params[:pc_id] = params[:c_id] = nil
    end
  end

  def get_products_by_categories
    gid = params[:gc_id]
    pid = params[:pc_id]
    cid = params[:c_id]
    category_arr = []
    if gid.present? && pid.present? && cid.present?
      category_arr << gid.to_i
      category_arr << pid.to_i
      category_arr << cid.to_i
    elsif gid.present? && pid.present?
      category_arr << gid.to_i
      category_arr << pid.to_i
      category_arr << Category.find_by(id: pid).childrens.pluck(:id)
    elsif gid.present?
      category_arr << gid.to_i
      p_cates = Category.find_by(id: gid).childrens
      category_arr << p_cates.pluck(:id)
      p_cates.each do |p_id|
        category_arr << Category.find_by(id: p_id).childrens.pluck(:id)
      end
    end
    category_arr = category_arr.flatten
    return Product.all unless category_arr.size > 0
    Product.by_categories category_arr
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_data_show, only: :show
  before_action :load_data_index, only: :index
  before_action :load_left_menu_by_category, only: [:show, :index]

  ORDER_ATTRS = %i(username phone email received_address pay_address)

  def index
  end

  def show
  end

  def order
    @product = Product.find params[:id]
    respond_to do |format|
      format.js{render layout: false}
    end
  end

  def send_order
    respond_to do |format|
      @product = Product.find params[:id]
      @data_valid = ORDER_ATTRS.all?{|type| params[type].present?}
      user_info = params.as_json(only: ORDER_ATTRS).symbolize_keys
      return unless @data_valid
      ProductOrderMailer.order(user_info, @product).deliver_later
      format.js do
        render layout: false
      end
    end
  end

  private
  def load_left_menu_data is_current_category = false
    mang_ong = []
    ongs = Category.where(level: Settings.category.highest_level)
    if is_current_category
      ongs = Category.where(id: @category_lv_1.id)
    end
    ongs.each do |ong|
      bos = ong.childrens
      mang_bo = []
      bos.each do |bo|
        mang_con = bo.childrens
        mang_bo << [bo, mang_con]
      end
      mang_ong << [ong, mang_bo]
    end
    @categories = mang_ong
    get_new_product
    load_breadcrum
    load_products_block
    load_brand_exist
  end

  def load_products_block
    if category = Category.find_by(id: params[:category_id])
      if category.level == Settings.category.middle_level
        if category.childrens
          @childs = []
          category.childrens.each do |child|
            products = params[:brand_id] ? child.products
              .where(brand_id: params[:brand_id]) : child.products
            if products.size > 0
              @childs << {name: child.name, id: child.id, products: products
                .order(category_order: :asc).limit(Settings.limit.product_block)}
            end
          end

        end
      elsif category.level == Settings.category.highest_level
        if category.childrens
          @childs = []
          category.childrens.each do |child|
            products = child.product_for_block_list(params[:brand_id])
            if products.size > 0
              @childs << {name: child.name, id: child.id, products: products}
            end
          end
        end
      end
      unless category.level == Settings.category.lowest_level
        @products = []
        @childs.each do |child|
          @products += child[:products]
        end
        @products = Kaminari.paginate_array(@products.flatten)
          .page(params[:page]).per(Settings.limit.paginate.products)
        limit = Settings.limit.paginate.products/Settings.limit.product_block
        page = params[:page] ? params[:page].to_i : 1
        @childs = @childs.select.with_index do |c, index|
          limit*(page-1) <= index && index <= page*limit - 1
        end
      end
    end
  end

  def load_brand_exist
    return unless @category
    @brands = Brand.where(id: list_products(@category).pluck(:brand_id).uniq)
      .order(:name)
  end

  def load_left_menu_by_category
    @category = Category.find_by id: params[:category_id]
    if product = Product.find_by(id: params[:id])
      @category = product.categories.first
    end
    return load_left_menu_data unless @category
    if @category.level == Settings.category.middle_level
      @category_lv_1 = @category.parents.first
    elsif @category.level == Settings.category.lowest_level
      @category_lv_1 = @category.parents.first.parents.first
    elsif @category.level == Settings.category.highest_level
      @category_lv_1 = @category
    end
    return load_left_menu_data unless @category_lv_1
    load_left_menu_data true
  end

  def load_breadcrum
    if params[:category_id]
      category = Category.find_by id: params[:category_id]
      @breads = [{title: category.name, link: ""}]
      if parent = category.parents.first
        @breads << {title: parent.name, link: products_path(category_id: parent.id)}
        if grand_parent = parent.parents.first
          @breads << {title: grand_parent.name, link: products_path(category_id: grand_parent.id)}
        end
      end
      @breads << {title: "Tất cả sản phẩm", link: products_path}
      @breads = @breads.reverse
    elsif params[:id]
      @breads = [{title: @product.name, link: ""}]
      if category = @product.categories.first
        @breads << {title: category.name, link: products_path(category_id: category.id)}
        if parent = category.parents.first
          @breads << {title: parent.name, link: products_path(category_id: parent.id)}
          if grand_parent = parent.parents.first
            @breads << {title: grand_parent.name, link: products_path(category_id: grand_parent.id)}
          end
        end
      end
      @breads = @breads.reverse
    elsif params[:brand_id]
      brand = Brand.find_by id: params[:brand_id]
      @breads = [{title: "Hãng sản xuất", link: products_path()}]
      @breads << {title: brand.name, link: ""}
    elsif params[:field_id]
      field = Field.find_by id: params[:field_id]
      @breads = [{title: "Lĩnh vực", link: products_path()}]
      @breads << {title: field.name, link: ""}
    else
      @breads = [{title: "Tất cả sản phẩm", link: ""}]
    end
  end

  def load_data_show
    @product = Product.find_by id: params[:id]
    @documents = @product.mediums.where(media_type: 0)
    @videos = @product.mediums.where(media_type: 1)
    @related_products = []
    if category = @product.categories.first
      @related_products = Product.where(id: category.products.pluck(:id).uniq)
        .limit Settings.limit.related_products
    end
  end

  def load_data_index
    params[:page] ||= 1
    if params[:category_id]
      menu_item = Category.find_by id: params[:category_id]
    elsif params[:field_id]
      menu_item = Field.find_by id: params[:field_id]
    elsif params[:brand_id]
      menu_item = Brand.find_by id: params[:brand_id]
    end
    @products_from_menu = get_products(menu_item).page(params[:page])
      .per(Settings.limit.paginate.products)

    unless @products_from_menu.blank?
      @title = menu_item ? menu_item.name : "Tất cả sản phẩm"
      get_number_show_product
    end

    if (q = params[:query]).present?
      found_products = Product.search(body: {query: {match: {_all: q}}})
      @products_from_menu = get_products(Product.by_ids(found_products.map(&:id)))
        .page(params[:page]).per(Settings.limit.paginate.products)
      get_number_show_product if @products_from_menu.present?
    end
  end

  def get_number_show_product
    limit = Settings.limit.paginate.products
    @from = (params[:page].to_i - 1) * limit + 1
    if @products_from_menu.count >= limit
      @to = params[:page].to_i * limit
    else
      @to = @products_from_menu.total_count
    end
  end

  def get_products menu_item
    products = menu_item.respond_to?(:size) ? menu_item :
      (menu_item.present? ? get_products_for_menu_item(menu_item) : Product.all)
    if params[:sort_by] == Product::SORT_FIELDS[:name]
      sort_by_price products.order(name: :asc)
    elsif params[:sort_by] == Product::SORT_FIELDS[:date]
      sort_by_price products.order(created_at: :desc)
    elsif params[:sort_by] == Product::SORT_FIELDS[:price]
      sort_by_price products.order(price: :asc)
    elsif params[:sort_by] == Product::SORT_FIELDS[:price_desc]
      sort_by_price products.order(price: :desc)
    else
      sort_by_price products
    end
  end

  def get_products_for_menu_item menu_item
    return menu_item.products unless menu_item.class.name == Category.name
    category = menu_item
    if params[:brand_id]
      list_products(category).where(brand_id: params[:brand_id])
    else
      list_products category
    end
  end

  def list_products category
    list_categories = [category.id]
    if c = category.childrens
      list_categories << c.pluck(:id)
      c.each do |children|
        if sub_c = children.childrens
          list_categories << sub_c.pluck(:id)
        end
      end
    end
    list_categories = list_categories.flatten
    Product.by_categories list_categories
  end

  def sort_by_price products
    if params[:min_price] && params[:max_price]
      products.sort_in_range [params[:min_price].to_i, params[:max_price].to_i]
    elsif params[:min_price]
      products.sort_from_price params[:min_price].to_i
    elsif params[:max_price]
      products.sort_to_price params[:max_price].to_i
    else
      products
    end
  end

  def get_new_product
    label_id = Label.where(short_title: "hot").first.id
    @new_products = Product.where(label_id: label_id)
      .limit(Settings.limit.new_products)
  end
end

app/views/admin/products/_category_field.html.erb
<% @g_categories.each_with_index do |g_category, index| %>
  <div class="row show-grid category-block col-xs-2">
    <div class="form-group">
      <p class="g-category"><%= g_category.name %></p>
    </div>
    <div class="form-group">
      <button type="button" class="btn btn-xs btn-danger remove-selected-category" data-id="<%= index %>">Bỏ chọn</button>
    </div>
    <div class="form-group">
      <% list_order = @category_attrs && @category_attrs[index] ? @category_attrs[index][:list_order] : "" %>
      <% category_id = @category_attrs && @category_attrs[index] ? @category_attrs[index][:category_id] : 0 %>
      <input type="number" class="form-control category-order" id="category-order<%= index %>" placeholder="Thứ tự"
        value="<%= list_order %>">
    </div>
    <div class="funkyradio">
      <% g_category.childrens.each do |p_category| %>
        <div class="funkyradio-success">
          <input type="radio" name="category<%= index %>" id="parent-category<%= p_category.id %>" value="<%= p_category.id %>"
            data-name="<%= p_category.name %>" <%= 'checked' if p_category.id == category_id %> />
          <label for="parent-category<%= p_category.id %>" title="<%= p_category.name %>" class="category-label"><%= p_category.name %></label>
        </div>
        <div class="form-group category-group">
          <% p_category.childrens.each do |category| %>
            <div class="funkyradio-primary">
              <input type="radio" name="category<%= index %>" id="category<%= category.id %>" value="<%= category.id %>"
                data-name="<%= category.name %>" <%= 'checked' if category.id == category_id %> />
              <label for="category<%= category.id %>" title="<%= category.name %>" class="category-label"><%= category.name %></label>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/products/_category_modal.html.erb
<div class="modal fade" id="product-category" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close" id="auto-comfirm-category-product" data-dismiss="modal" aria-label="close">&times;</a>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title custom_align" id="Heading">Chọn danh mục</h4>
      </div>
      <div class="modal-body">
        <div class="row show-grid">
          <div id="category-fields-for">
            <%= f.fields_for(:product_categories) do |ff| %>
              <%= ff.number_field :category_id, class: "form-control hidden" %>
              <%= ff.number_field :list_order, class: "form-control hidden" %>
            <% end %>
          </div>
          <%= render "category_field", f: f %>
        </div>
      </div>
      <div class="modal-footer ">
        <button type="button" class="btn btn-success" id="confirm-category-product" data-size="<%= @g_categories.count %>" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/_detail_field.html.erb
<div class="row show-grid">
  <div class="form-group form-group-part col-xs-6">
    <strong>Tên sản phẩm</strong> </br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group form-group-part col-xs-6">
    <div class="col-xs-6 price-form">
      <strong>Giá (.000 ₫)</strong> </br>
      <%= f.number_field :price, class: "form-control" %>
    </div>
    <div class="col-xs-6 price-form">
      <strong>Giá sale (.000 ₫)</strong> </br>
      <%= f.number_field :discount_price, class: "form-control" %>
    </div>
  </div>
</div>

<div class="row show-grid">
  <div class="form-group form-group-part col-xs-6">
    <div class="col-xs-6 parameter-form">
      <strong>Định dạng thông số</strong> </br>
      <%= f.select :is_parameter_table, [['Dạng text', false], ['Dạng bảng', true]], {}, { class: "form-control"} %>
    </div>
    <div class="col-xs-2">
      <strong>Thông số</strong> </br>
      <%= link_to "Nhập", "#product-parameter", :class => "btn btn-success", "data-toggle" => "modal" %>
    </div>
    <div class="col-xs-4">
      <p class="product-parameter-span multi-line"></p>
    </div>
  </div>
  <div class="form-group form-group-part col-xs-6">
    <div class="col-xs-6 price-form">
      <strong>Mã sản phẩm</strong> </br>
      <%= f.text_field :model, class: "form-control" %>
    </div>
    <div class="col-xs-6 price-form">
      <strong>Hãng</strong> </br>
      <%= f.select :brand_id, options_for_select(Brand.all.map{|c| [c.name, c.id]}), {include_blank: "Chọn hãng"}, { :class => 'form-control' } %>
    </div>
  </div>
</div>


<div class="row show-grid">
  <div class="form-group form-group-part col-xs-6">
    <strong>Mô tả ngắn</strong> </br>
    <%= f.text_area :short_description, class: "form-control", rows: 5 %>
  </div>
  <div class="form-group form-group-part col-xs-6">
    <strong>Mô tả</strong> </br>
    <%= f.text_area :description, class: "form-control", rows: 5 %>
  </div>
</div>

<div class="modal fade" id="product-parameter" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal" aria-label="close">&times;</a>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title custom_align" id="Heading">Thông số sản phẩm</h4>
      </div>
      <div class="modal-body">
        <%= f.text_area :parameter, class: "form-control hidden", placeholder: "Nhập thông số" %>
        <div id="product-parameter-table-div">
          <table class="table table-bordered" id="product-parameter-table">
            <thead>
              <tr>
                <th>Thuộc tính</th>
                <th>Giá trị</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><input type="text" class="form-control"/></td>
                <td><input type="text" class="form-control"/></td>
                <td><button type="button" class="btn btn-danger delete-param-product">Xóa</button></td>
              </tr>
              <tr>
                <td><input type="text" class="form-control"/></td>
                <td><input type="text" class="form-control"/></td>
                <td><button type="button" class="btn btn-danger delete-param-product">Xóa</button></td>
              </tr>
              <tr>
                <td><input type="text" class="form-control"/></td>
                <td><input type="text" class="form-control"/></td>
                <td><button type="button" class="btn btn-danger delete-param-product">Xóa</button></td>
              </tr>
              <tr>
                <td><input type="text" class="form-control"/></td>
                <td><input type="text" class="form-control"/></td>
                <td><button type="button" class="btn btn-danger delete-param-product">Xóa</button></td>
              </tr>
              <tr>
                <td><input type="text" class="form-control"/></td>
                <td><input type="text" class="form-control"/></td>
                <td><button type="button" class="btn btn-danger delete-param-product">Xóa</button></td>
              </tr>
              <tr>
                <td><input type="text" class="form-control"/></td>
                <td><input type="text" class="form-control"/></td>
                <td><button type="button" class="btn btn-danger delete-param-product">Xóa</button></td>
              </tr>
            </tbody>
          </table>
          <button type="button" class="btn btn-success" id="add-param-product">Thêm thuộc tính</button>
        </div>
      </div>
      <div class="modal-footer ">
        <button type="button" class="btn btn-success" data-dismiss="modal" id="confirm-param-product">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/_document_field.html.erb
<div class="row show-grid category-block">
  <div class="funkyradio">
    <% @documents.each_with_index do |document, index| %>
      <% document_id = @document_attrs && @document_attrs.keys.include?(document.id.to_s) ? document.id : 0 %>

      <div class="funkyradio-success col-xs-12">
        <input type="checkbox" name="product-document" id="product-document<%= index %>" value="<%= document.id %>"
          data-name="<%= document.title %>" class="product-document" <%= 'checked' if document.id == document_id %> />
        <label for="product-document<%= index %>" title="<%= document.title %>" class="document-label"><%= document.title %></label>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/_field_field.html.erb
<div class="row show-grid category-block">
  <div class="funkyradio">
    <% @fields.each_with_index do |field, index| %>
      <% field_id = @field_attrs && @field_attrs.keys.include?(field.id.to_s) ? field.id : 0 %>
      <% list_order = @field_attrs ? @field_attrs[field.id.to_s] : "" %>

      <div class="funkyradio-success col-xs-9">
        <input type="checkbox" name="product-field" id="product-field<%= index %>" value="<%= field.id %>"
          data-name="<%= field.name %>" class="product-field" <%= 'checked' if field.id == field_id %> />
        <label for="product-field<%= index %>" title="<%= field.name %>" class="field-label"><%= field.name %></label>
      </div>
      <div class="col-xs-3">
        <input type="number" class="form-control field-order" id="field-order<%= index %>" placeholder="Thứ tự"
          value="<%= list_order %>">
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Sản phẩm</h1>
    </div>
  </div>
  <div class="row" id="product-table">
    <div class="col-lg-12">
      <div class="create-div">
        <%= link_to "Tạo mới", new_admin_product_path(), class: "btn btn-success" %>
        <%= link_to "Export", admin_imports_path(format: "xlsx"), class: "btn btn-primary", id: "button-export-products" %>
        <input type="hidden" id="product-export-ids" value="">
      </div>
      <%= render "shared/flash" %>
      <div class="category-group">
        <%= form_tag({}, {:method => :get, class: "form-tag-group"}) do %>
          <div class="col-xs-6 col-md-3">
            <strong>Cấp 1</strong>
            <%= select_tag :gc_id, options_for_select(@g_categories.map{|c| [c.name, c.id] },
              selected: params[:gc_id]), include_blank: "Tất cả danh mục",
              :onchange => "this.form.submit();", class: "form-control" %>
          </div>
          <% if params[:gc_id].present? && @p_categories.present? %>
            <div class="col-xs-6 col-md-3">
              <strong>Cấp 2</strong>
              <%= select_tag :pc_id, options_for_select(@p_categories.map{|c| [c.name, c.id] },
                selected: params[:pc_id]), include_blank: "Tất cả danh mục",
                :onchange => "this.form.submit();", class: "form-control" %>
            </div>
          <% end %>
          <% if params[:pc_id].present? && @categories.present? %>
            <div class="col-xs-6 col-md-3">
              <strong>Cấp 3</strong>
              <%= select_tag :c_id, options_for_select(@categories.map{|c| [c.name, c.id] },
                selected: params[:c_id]), include_blank: "Tất cả danh mục",
                :onchange => "this.form.submit();", class: "form-control" %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-product">
          <thead>
            <tr>
              <th>Export</th>
              <th>Ảnh</th>
              <th>Tên</th>
              <th>Mã sản phẩm</th>
              <th>Giá</th>
              <th>Mô tả ngắn</th>
              <th>Hãng</th>
              <th>Danh mục</th>
              <th>Lĩnh vực</th>
              <th class="center"></th>
              <th class="center"></th>
            </tr>
          </thead>
          <tbody>
            <% @products.each_with_index do |product, index| %>
              <tr class="odd gradeX" id="product<%= product.id %>">
                <td class="product-cb">
                  <input type="checkbox" value="<%= product.id %>" class="product-cb-id">
                </td>
                <td>
                  <%= image_tag(product.product_images.first.try(:url), size: 100) if product.product_images.first.try(:url) %>
                </td>
                <td>
                  <p><%= product.try(:name) %></p>
                </td>
                <td>
                  <p><%= product.try(:model) %></p>
                </td>
                <td>
                  <p><%= product.try(:price_currency) %></p>
                </td>
                <td>
                  <p><%= product.try(:short_description) %></p>
                </td>
                <td>
                  <p><%= product.try(:brand).try(:name) %></p>
                </td>
                <td>
                  <p><%= product.try(:category_name) %></p>
                </td>
                <td>
                  <p><%= product.try(:field_name) %></p>
                </td>
                <td class="center">
                  <%= link_to "Sửa", edit_admin_product_path(product), class: "btn btn-primary" %>
                </td>
                <td class="center">
                  <p data-placement="top" data-toggle="tooltip" title="Xóa">
                    <button class="btn btn-danger button-delete-product"
                      data-title="Xóa"
                      data-toggle="modal"
                      data-target="#delete-product"
                      data-product-id="<%= product.id %>"
                      data-product-name="<%= product.name %>">
                      Xóa
                    </button>
                  </p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="modal fade" id="delete-product" tabindex="-1" role="dialog" aria-labelledby="delete" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <a href="#" class="close" data-dismiss="modal" aria-label="close">&times;</a>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
          <h4 class="modal-title custom_align" id="Heading">Xóa sản phẩm</h4>
        </div>
        <div class="modal-body">
          <div class="alert alert-danger">Bạn có chắc chắn xóa sản phẩm <strong class="delete-product-name"></strong> không?</div>
        </div>
        <div class="modal-footer ">
          <button type="button" class="btn btn-success" id="button-delete-product-confirm" data-id="">Có</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Không</button>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
  </div>
</div>