config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  root "pages#home"
  resource :subcribers
  resources :products, only: [:show, :index] do
    member do
      get :order
      post :send_order
    end
  end
  resources :blogs, only: [:show, :index]
  resources :medias, only: [:show, :index]
  resources :contacts, only: [:index, :create]
  get "/products" => "products#index", as: :search_product

  namespace :admin do
    root "home#show"
    resources :home, only: [:show]
    resources :fields
    resources :brands
    resource :company, only: [:show, :update, :edit]
    resources :sliders
    resources :catalogs
    resources :products
    resources :categories
    resources :imports
    resources :tags
    resources :subscribers
    get "/edit_company" => "companies#edit", as: :edit_company
    resources :fields
    resources :medias
    devise_for :admins, :controllers => {:sessions => 'admin/sessions',
      :passwords => 'admin/passwords' }, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
    resources :blogs
    post "/templates/:id" => "templates#show", defaults: {format: "json"}, as: :template
    resources :templates, only: [:index, :create, :update, :destroy]
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :load_products, only: :index
  before_action :load_product, only: [:new, :create, :edit, :update, :destroy]

  def index
  end

  def new
    @product = Product.new
    @product.product_categories.build
    @product.product_images.build
    @product.product_images.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Tạo mới sản phẩm #{@product.name} thành công!"
      redirect_to admin_products_path
    else
      @category_attrs = category_params
      @field_attrs = field_params
      @video_attrs = media_params
      @document_attrs = media_params
      flash[:danger] = @product.errors.full_messages
      render :new
    end
  end

  def edit
    @category_attrs = category_params
    @field_attrs = field_params
    @video_attrs = media_params
    @document_attrs = media_params
    unless @product.product_images.present?
      @product.product_images.build
      @product.product_images.build
    end
  end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = "Sửa sản phẩm #{@product.name} thành công!"
      redirect_to admin_products_path
    else
      @category_attrs = category_params
      @field_attrs = field_params
      @video_attrs = media_params
      @document_attrs = media_params
      flash[:danger] = @product.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = "Xóa sản phẩm #{@product.name} thành công!"
    else
      flash[:danger] = "Lỗi! Xóa sản phẩm không thành công."
    end
    redirect_to admin_products_path()
  end
  private
  def product_params
    params.require(:product).permit(Product::PRODUCT_ATTRIBUTES,
      product_images_attributes: Product::PRODUCT_IMAGE_ATTRIBUTES,
      product_categories_attributes: Product::PRODUCT_CATEGORY_ATTRIBUTES,
      product_fields_attributes: Product::PRODUCT_FIELD_ATTRIBUTES,
      product_media_relations_attributes: Product::PRODUCT_MEDIA_ATTRIBUTES)
  end

  def load_products
    get_categories
    @products = get_products_by_categories
  end

  def load_product
    @product = Product.find_by id: params[:id]
    get_categories
    get_fields
    get_medias
  end

  def field_params
    arr = {}
    if @product.product_fields
      @product.product_fields.each do |field|
        arr[field.field_id.to_s] = field.list_order
      end
    else
      params[:product][:product_fields_attributes].each do |key, value|
        arr[value[:field_id]] = value[:list_order]
      end
    end
    arr
  end

  def media_params
    arr = {}
    if @product.product_media_relations
      @product.product_media_relations.each do |medium|
        arr[medium.medium_id.to_s] = medium.medium_id.to_s
      end
    else
      params[:product][:product_media_relations_attributes].each do |key, value|
        arr[value[:medium_id]] = value[:medium_id]
      end
    end
    arr
  end

  def category_params
    arr = {}
    if @product.product_categories
      @g_categories.each_with_index do |c, index|
        @product.product_categories.each do |pc|
          if c.all_children_ids.include? pc.category_id
            arr[index] = {category_id: pc.category_id, list_order: pc.list_order}
            break
          end
        end
      end
    else
      @g_categories.each_with_index do |c, index|
        params[:product][:product_categories_attributes].each do |key, value|
          if c.all_children_ids.include? value[:category_id].to_i
            arr[index] = {category_id: value[:category_id].to_i, list_order: value[:list_order]}
            break
          end
        end
      end
    end
    arr
  end

  def get_fields
    @fields = Field.all.order(menu_order: :asc)
  end

  def get_medias
    @videos = Medium.where(media_type: 1)
    @documents = Medium.where(media_type: 0)
  end

  def get_categories
    @g_categories = Category.where(level: Settings.category.highest_level)
    if params[:gc_id].present?
      g_category = Category.find_by id: params[:gc_id]
      @p_categories = g_category.childrens
    else
      params[:pc_id] = params[:c_id] = nil
    end

    if params[:pc_id].present? && @p_categories.pluck(:id).include?(params[:pc_id].to_i)
      p_category = Category.find_by id: params[:pc_id]
      @categories = p_category.childrens
    else
      params[:pc_id] = params[:c_id] = nil
    end
  end

  def get_products_by_categories
    gid = params[:gc_id]
    pid = params[:pc_id]
    cid = params[:c_id]
    category_arr = []
    if gid.present? && pid.present? && cid.present?
      category_arr << gid.to_i
      category_arr << pid.to_i
      category_arr << cid.to_i
    elsif gid.present? && pid.present?
      category_arr << gid.to_i
      category_arr << pid.to_i
      category_arr << Category.find_by(id: pid).childrens.pluck(:id)
    elsif gid.present?
      category_arr << gid.to_i
      p_cates = Category.find_by(id: gid).childrens
      category_arr << p_cates.pluck(:id)
      p_cates.each do |p_id|
        category_arr << Category.find_by(id: p_id).childrens.pluck(:id)
      end
    end
    category_arr = category_arr.flatten
    return Product.all unless category_arr.size > 0
    Product.by_categories category_arr
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_data_show, only: :show
  before_action :load_data_index, only: :index
  before_action :load_left_menu_by_category, only: [:show, :index]

  ORDER_ATTRS = %i(username phone email received_address pay_address)

  def index
  end

  def show
  end

  def order
    @product = Product.find params[:id]
    respond_to do |format|
      format.js{render layout: false}
    end
  end

  def send_order
    respond_to do |format|
      @product = Product.find params[:id]
      @data_valid = ORDER_ATTRS.all?{|type| params[type].present?}
      user_info = params.as_json(only: ORDER_ATTRS).symbolize_keys
      return unless @data_valid
      ProductOrderMailer.order(user_info, @product).deliver_later
      format.js do
        render layout: false
      end
    end
  end

  private
  def load_left_menu_data is_current_category = false
    mang_ong = []
    ongs = Category.where(level: Settings.category.highest_level)
    if is_current_category
      ongs = Category.where(id: @category_lv_1.id)
    end
    ongs.each do |ong|
      bos = ong.childrens
      mang_bo = []
      bos.each do |bo|
        mang_con = bo.childrens
        mang_bo << [bo, mang_con]
      end
      mang_ong << [ong, mang_bo]
    end
    @categories = mang_ong
    get_new_product
    load_breadcrum
    load_products_block
    load_brand_exist
  end

  def load_products_block
    if category = Category.find_by(id: params[:category_id])
      if category.level == Settings.category.middle_level
        if category.childrens
          @childs = []
          category.childrens.each do |child|
            products = params[:brand_id] ? child.products
              .where(brand_id: params[:brand_id]) : child.products
            if products.size > 0
              @childs << {name: child.name, id: child.id, products: products
                .order(category_order: :asc).limit(Settings.limit.product_block)}
            end
          end

        end
      elsif category.level == Settings.category.highest_level
        if category.childrens
          @childs = []
          category.childrens.each do |child|
            products = child.product_for_block_list(params[:brand_id])
            if products.size > 0
              @childs << {name: child.name, id: child.id, products: products}
            end
          end
        end
      end
      unless category.level == Settings.category.lowest_level
        @products = []
        @childs.each do |child|
          @products += child[:products]
        end
        @products = Kaminari.paginate_array(@products.flatten)
          .page(params[:page]).per(Settings.limit.paginate.products)
        limit = Settings.limit.paginate.products/Settings.limit.product_block
        page = params[:page] ? params[:page].to_i : 1
        @childs = @childs.select.with_index do |c, index|
          limit*(page-1) <= index && index <= page*limit - 1
        end
      end
    end
  end

  def load_brand_exist
    return unless @category
    @brands = Brand.where(id: list_products(@category).pluck(:brand_id).uniq)
      .order(:name)
  end

  def load_left_menu_by_category
    @category = Category.find_by id: params[:category_id]
    if product = Product.find_by(id: params[:id])
      @category = product.categories.first
    end
    return load_left_menu_data unless @category
    if @category.level == Settings.category.middle_level
      @category_lv_1 = @category.parents.first
    elsif @category.level == Settings.category.lowest_level
      @category_lv_1 = @category.parents.first.parents.first
    elsif @category.level == Settings.category.highest_level
      @category_lv_1 = @category
    end
    return load_left_menu_data unless @category_lv_1
    load_left_menu_data true
  end

  def load_breadcrum
    if params[:category_id]
      category = Category.find_by id: params[:category_id]
      @breads = [{title: category.name, link: ""}]
      if parent = category.parents.first
        @breads << {title: parent.name, link: products_path(category_id: parent.id)}
        if grand_parent = parent.parents.first
          @breads << {title: grand_parent.name, link: products_path(category_id: grand_parent.id)}
        end
      end
      @breads << {title: "Tất cả sản phẩm", link: products_path}
      @breads = @breads.reverse
    elsif params[:id]
      @breads = [{title: @product.name, link: ""}]
      if category = @product.categories.first
        @breads << {title: category.name, link: products_path(category_id: category.id)}
        if parent = category.parents.first
          @breads << {title: parent.name, link: products_path(category_id: parent.id)}
          if grand_parent = parent.parents.first
            @breads << {title: grand_parent.name, link: products_path(category_id: grand_parent.id)}
          end
        end
      end
      @breads = @breads.reverse
    elsif params[:brand_id]
      brand = Brand.find_by id: params[:brand_id]
      @breads = [{title: "Hãng sản xuất", link: products_path()}]
      @breads << {title: brand.name, link: ""}
    elsif params[:field_id]
      field = Field.find_by id: params[:field_id]
      @breads = [{title: "Lĩnh vực", link: products_path()}]
      @breads << {title: field.name, link: ""}
    else
      @breads = [{title: "Tất cả sản phẩm", link: ""}]
    end
  end

  def load_data_show
    @product = Product.find_by id: params[:id]
    @documents = @product.mediums.where(media_type: 0)
    @videos = @product.mediums.where(media_type: 1)
    @related_products = []
    if category = @product.categories.first
      @related_products = Product.where(id: category.products.pluck(:id).uniq)
        .limit Settings.limit.related_products
    end
  end

  def load_data_index
    params[:page] ||= 1
    if params[:category_id]
      menu_item = Category.find_by id: params[:category_id]
    elsif params[:field_id]
      menu_item = Field.find_by id: params[:field_id]
    elsif params[:brand_id]
      menu_item = Brand.find_by id: params[:brand_id]
    end
    @products_from_menu = get_products(menu_item).page(params[:page])
      .per(Settings.limit.paginate.products)

    unless @products_from_menu.blank?
      @title = menu_item ? menu_item.name : "Tất cả sản phẩm"
      get_number_show_product
    end

    if (q = params[:query]).present?
      found_products = Product.search(body: {query: {match: {_all: q}}})
      @products_from_menu = get_products(Product.by_ids(found_products.map(&:id)))
        .page(params[:page]).per(Settings.limit.paginate.products)
      get_number_show_product if @products_from_menu.present?
    end
  end

  def get_number_show_product
    limit = Settings.limit.paginate.products
    @from = (params[:page].to_i - 1) * limit + 1
    if @products_from_menu.count >= limit
      @to = params[:page].to_i * limit
    else
      @to = @products_from_menu.total_count
    end
  end

  def get_products menu_item
    products = menu_item.respond_to?(:size) ? menu_item :
      (menu_item.present? ? get_products_for_menu_item(menu_item) : Product.all)
    if params[:sort_by] == Product::SORT_FIELDS[:name]
      sort_by_price products.order(name: :asc)
    elsif params[:sort_by] == Product::SORT_FIELDS[:date]
      sort_by_price products.order(created_at: :desc)
    elsif params[:sort_by] == Product::SORT_FIELDS[:price]
      sort_by_price products.order(price: :asc)
    elsif params[:sort_by] == Product::SORT_FIELDS[:price_desc]
      sort_by_price products.order(price: :desc)
    else
      sort_by_price products
    end
  end

  def get_products_for_menu_item menu_item
    return menu_item.products unless menu_item.class.name == Category.name
    category = menu_item
    if params[:brand_id]
      list_products(category).where(brand_id: params[:brand_id])
    else
      list_products category
    end
  end

  def list_products category
    list_categories = [category.id]
    if c = category.childrens
      list_categories << c.pluck(:id)
      c.each do |children|
        if sub_c = children.childrens
          list_categories << sub_c.pluck(:id)
        end
      end
    end
    list_categories = list_categories.flatten
    Product.by_categories list_categories
  end

  def sort_by_price products
    if params[:min_price] && params[:max_price]
      products.sort_in_range [params[:min_price].to_i, params[:max_price].to_i]
    elsif params[:min_price]
      products.sort_from_price params[:min_price].to_i
    elsif params[:max_price]
      products.sort_to_price params[:max_price].to_i
    else
      products
    end
  end

  def get_new_product
    label_id = Label.where(short_title: "hot").first.id
    @new_products = Product.where(label_id: label_id)
      .limit(Settings.limit.new_products)
  end
end

app/views/products/_image_detail.html.erb
<div class="images">
  <div class="easyzoom is-ready easyzoom--overlay easyzoom--with-thumbnails">
    <a href="" class="woocommerce-main-image">
      <%= image_tag @product.product_images.first.url, size: '400', title: @product.product_images.first.title, alt: @product.product_images.first.alt, 'data-zoom-image': @product.product_images.first.url, id: 'zoom' %>
    </a>
  </div>

  <div class="swiper-carousel-container">
    <div id="swiper-carousel-59e9bc5f03f8c" class="tm-willard-carousel swiper-container swiper-container-horizontal" style="cursor: -webkit-grab;">
      <div class="swiper-wrapper" id="gallery_01">
        <% @product.product_images.each do |image| %>
          <a href="" data-image="<%= image.url %>" data-zoom-image="<%= image.url %>" class="thumb-image-product">
            <%= image_tag image.url, size: "10", title: image.title, alt: image.alt %>
          </a>
        <% end %>
      </div>

      <script>
        //initiate the plugin and pass the id of the div containing gallery images
        $("#zoom").elevateZoom({gallery:'gallery_01', cursor: 'pointer', galleryActiveClass: 'active', imageCrossfade: true, scrollZoom: true, tintOpacity: 0.5});

        //pass the images to Fancybox
        $("#zoom").bind("click", function(e) {
          var ez =   $('#zoom').data('elevateZoom');
          $.fancybox(ez.getGalleryList());
          return false;
        });
      </script>
    </div>
  </div>
</div>

app/views/products/_left_new_product.html.erb
<div data-sidebar="shop-sidebar">
  <aside id="tm_willard_products-4" class="widget woocommerce tm_willard_widget_products">
    <h2 class="widget-title title-font-em">Sản phẩm mới</h2>
    <ul class="product_list_widget">
      <% @new_products.each do |product| %>
        <li>
          <%= link_to product_path(product), title: product.name do %>
            <%= image_tag product.product_images.first.url, size: '210', title: product.product_images.first.title, alt: product.product_images.first.alt if product.product_images.first.url%>
          <% end %>
          <!-- <div class="product-widget-categories">
            <a href="" rel="tag">Cutters</a>,
            <a href="" rel="tag">Drills</a>,
            <a href="" rel="tag">Gardenign Tools</a>
          </div> -->
          <div class="product-widget-categories">
            <% product.categories.each do |category| %>
              <%= link_to "#{category.name} ", products_path(category_id: category.id), rel: "tag" %>
            <% end %>
          </div>
          <span class="product-title">
            <%= link_to product.name, product_path(product), title: product.name, class: "product-title-custom" %>
          </span>
          <span class="woocs_price_code" data-product-id="274">
            <% if product.discount_price_currency.present? %>
              <del>
                <span class="woocommerce-Price-amount amount"><%= product.price_currency %>
                  <span class="woocommerce-Price-currencySymbol">₫</span>
                </span>
              </del>
              <ins>
                <span class="woocommerce-Price-amount amount"><%= product.discount_price_currency %>
                  <span class="woocommerce-Price-currencySymbol">₫</span>
                </span>
              </ins>
            <% else %>
              <span class="woocommerce-Price-amount amount"><%= product.price_currency %>
                <span class="woocommerce-Price-currencySymbol">₫</span>
              </span>
            <% end %>
          </span>
          <div class="add_to_cart_button-wrap">
            <%= link_to "MUA", order_product_path(product), remote: true, rel: "nofollow",
              "data-product-id": product.id, class: "button product_type_variable add_to_cart_button" %>
          </div>
        </li>
      <% end %>
    </ul>
  </aside>
</div>

app/views/products/_product_block.html.erb
<article id="post-73" class="posts-list__item card post-73 post type-post status-publish format-standard has-post-thumbnail hentry category-accessories category-diy-home category-tips tag-drill tag-hammer tag-hand-tools tag-power-tools has-thumb">
  <figure class="post-thumbnail">
    <span class="post-cats">
      <%= link_to block[:name], products_path(category_id: block[:id]) %>
    </span>
  </figure>
  <div class="products row">
    <% block[:products].each do |product|%>
      <%= render "product_field", product: product, col: 3 %>
    <% end %>
  </div>
  <div class="block-footer">
    <%= link_to products_path(category_id: block[:id]), class: 'btn btn-secondary' do %>
      <span class="link__text">Xem thêm</span>
    <% end %>
  </div>
</article>

app/views/products/_product_field.html.erb
<div class="post-215 type-product status-publish has-post-thumbnail hentry product_shipping_class-class-2 has-thumb col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-3 col-xxl-3 product">
  <div class="block_product_inner">
    <div class="block_product_thumbnail">
      <a href="">
        <div class="tm-thumbs-wrap effect-fade">
          <div class="tm-thumbs-wrap__inner">
            <%= link_to product_path(product), title: product.name do %>
              <%= image_tag product.product_images.first.url, size: '340', title: product.product_images.first.title, alt: product.product_images.first.alt if product.product_images.first.try(:url)%>
              <%= image_tag product.product_images.second.url, size: '340', title: product.product_images.second.title, alt: product.product_images.second.alt if product.product_images.second.try(:url)%>
            <% end %>
          </div>
        </div>
      </a>
    </div>
    <div class="block_product_content">
      <h3>
        <%= link_to product.name, product_path(product), class: "woocommerce-LoopProduct-link", title: product.name %>
      </h3>
      <span class="price">
        <span class="woocs_price_code" data-product-id="215">
          <span class="woocommerce-Price-amount amount"><%= product.price_currency %>
            <span class="woocommerce-Price-currencySymbol">₫</span>
          </span>
        </span>
      </span>

      <div class="price-add-to-cart-wrap">
        <%= link_to "MUA", order_product_path(product), remote: true, rel: "nofollow",
          "data-product-id": product.id, class: "button product_type_variable add_to_cart_button" %>
      </div>
    </div>
  </div>
</div>

app/views/products/_related_products_sidebar.html.erb
<div class="related products">
  <h5>Sản phẩm liên quan</h5>
  <div class="swiper-carousel-container">
    <div id="swiper-carousel-59e9bc5f37e5e" class="tm-willard-carousel swiper-container swiper-container-horizontal" style="cursor: -webkit-grab;">
      <div class="swiper-wrapper">
        <% @related_products.each do |product| %>
          <div class="post-264 product type-product status-publish has-post-thumbnail hentry product_shipping_class-class-2 has-thumb swiper-slide swiper-slide-next <%= product == @related_products.last ? 'relate-last' : 'relate' %>" style="width: 23%;">
            <div class="block_product_inner">
              <div class="block_product_thumbnail">
                <a href="" class="woocommerce-LoopProduct-link">
                  <div class="tm-thumbs-wrap effect-fade">
                    <div class="tm-thumbs-wrap__inner">
                      <%= link_to product_path(product), title: product.name do %>
                        <%= image_tag product.product_images.first.url, size: '340', title: product.product_images.first.title, alt: product.product_images.first.alt if product.product_images.first.url%>
                        <%= image_tag product.product_images.second.url, size: '340', title: product.product_images.second.title, alt: product.product_images.second.alt if product.product_images.second.url%>
                      <% end %>
                    </div>
                  </div>
                </a>
                <div class="wishlist_compare_button_block">
                  <div class="tm-quick-view">
                    <a href="" class="tm-quick-view-btn" data-action="quick-view-button" data-product="264">Quick View</a>
                  </div>
                </div>
              </div>
              <div class="block_product_content">
                <ul class="product-categories">
                  <li>
                    <% product.categories.each do |category| %>
                      <%= link_to "#{category.name} ", products_path(category_id: category.id), rel: "tag" %>
                    <% end %>
                  </li>
                </ul>
                <h3><a href=""><%= link_to product.name, product_path(product) %></a></h3>
                <div class="price-add-to-cart-wrap">
                  <span class="price">
                    <span class="woocs_price_code" data-product-id="264">
                      <% if product.discount_price_currency.present? %>
                        <del>
                          <span class="woocommerce-Price-amount amount"><%= product.price_currency %>
                            <span class="woocommerce-Price-currencySymbol">₫</span>
                          </span>
                        </del>
                        <ins>
                          <span class="woocommerce-Price-amount amount"><%= product.discount_price_currency %>
                            <span class="woocommerce-Price-currencySymbol">₫</span>
                          </span>
                        </ins>
                      <% else %>
                        <span class="woocommerce-Price-amount amount"><%= product.price_currency %>
                          <span class="woocommerce-Price-currencySymbol">₫</span>
                        </span>
                      <% end %>
                    </span>
                  </span>
                  <%= link_to "MUA", order_product_path(product), remote: true, rel: "nofollow",
                    "data-product-id": product.id, class: "button product_type_simple add_to_cart_button ajax_add_to_cart" %>
                </div>

                <!-- <span class="price">
                  <span class="woocs_price_code" data-product-id="215">
                    <span class="woocommerce-Price-amount amount">154.00
                      <span class="woocommerce-Price-currencySymbol">$</span>
                    </span>
                     –
                    <span class="woocommerce-Price-amount amount">198.00
                      <span class="woocommerce-Price-currencySymbol">$</span>
                    </span>
                  </span>
                </span> -->
              </div>
            </div>
          </div>
        <% end %>


      </div>
    </div>
    <div id="swiper-carousel-59e9bc5f37e5e-next" class="swiper-button-next button-next swiper-button-disabled" style="display: block;"></div>
    <div id="swiper-carousel-59e9bc5f37e5e-prev" class="swiper-button-prev button-prev swiper-button-disabled" style="display: block;"></div>
  </div>
</div>

app/views/products/order.js.erb
$('#product-order-placeholder').html('<%= j render("shared/order_form", product: @product) %>')
$('#product-order-modal').modal('show')

app/views/products/send_order.js.erb
$('#product-order-modal').modal('hide')
$('#order-result-placeholder').html('<%= j render("shared/order_result", data_valid: @data_valid) %>')
$('#order-result-modal').modal('show')

app/views/products/show.html.erb
<%= render "layouts/breadcrumbs" %>
<div class="site-content_wrap container">
  <div id="product-order-placeholder"></div>
  <div id="order-result-placeholder"></div>
  <div class="row">
    <div id="primary" class="col-xs-12 col-lg-10 col-lg-push-2">
      <main id="main" class="site-main" role="main">
        <div id="woo-primary" class="content-area willard">
          <div id="woo-main" class="site-main" role="main">
            <div id="product-215" class="post-215 product type-product status-publish has-post-thumbnail hentry product_shipping_class-class-2 has-thumb swiper-slide">
              <%= form_for @product, url: products_path do |f|%>
                <div class="row single_product_wrapper">

                  <!-- image -->
                  <div class="col-xl-5 col-md-12 col-sm-12 col-xs-12">
                    <div class="single-image-container">
                      <%= render "image_detail" %>
                    </div>
                  </div>

                  <!-- detail -->
                  <div class="col-xl-7 col-md-12 col-sm-12 col-xs-12">
                    <div class="summary entry-summary">
                      <span class="posted_in">
                        <% @product.categories.each do |category| %>
                          <%= link_to "#{category.name} ", products_path(category_id: category.id), rel: "tag" %>
                        <% end %>
                      </span>

                      <h1 class="product_title entry-title">
                        <%= @product.name %>
                      </h1>

                      <div class="product_meta">
                        <span class="sku_wrapper">Tình trạng: <span class="product-status" itemprop="sku">Còn hàng</span></span>
                        <span class="sku_wrapper">Mã sản phẩm: <span class="sku" itemprop="sku"><%= @product.model %></span></span>
                      </div>

                      <p class="price">
                        <span class="woocs_price_code" data-product-id="215">
                          <% if @product.discount_price_currency.present? %>
                            <del>
                              <span class="woocommerce-Price-amount amount"><%= @product.price_currency %>
                                <span class="woocommerce-Price-currencySymbol">₫</span>
                              </span>
                            </del>
                            <ins>
                              <span class="woocommerce-Price-amount amount"><%= @product.discount_price_currency %>
                                <span class="woocommerce-Price-currencySymbol">₫</span>
                              </span>
                            </ins>
                          <% else %>
                            <span class="woocommerce-Price-amount amount"><%= @product.price_currency %>
                              <span class="woocommerce-Price-currencySymbol">₫</span>
                            </span>
                          <% end %>
                        </span>
                      </p>

                      <div class="message">
                          <p>Để nhận được giá tốt nhất Quý khách vui lòng
                            <strong>"LIÊN HỆ"</strong> với số điện thoại phía trên hoặc click vào
                            <strong>"MUA"</strong> phía dưới.
                          </p>
                      </div>

                      <div class="woocommerce-product-details__short-description">
                        <p>Hãng sản xuất: <%= @product.brand.name %></p>
                      </div>

                      <div class="woocommerce-product-details__short-description">
                        <p><%= @product.short_description %></p>
                      </div>

                      <form class="cart" method="post" enctype="multipart/form-data" data-product_id="215" data-product_variations="[hash_array]" current-image="">
                        <div class="custom-cart-button">
                          <div class="">
                            <%= link_to "MUA", order_product_path(@product), remote: true, rel: "nofollow",
                              "data-product-id": @product.id, class: "single_add_to_cart_button button alt custom-button" %>
                          </div>
                        </div>
                      </form>
                    </div>
                    <!-- .summary -->
                  </div>
                </div>
                <%= render "description" %>
                <%= render "related_products_sidebar" %>
              <% end %>
            </div>
            <!-- #product-215 -->
          </div>
        </div>
      </main>
      <!-- #main -->
    </div>
    <!-- #primary -->
    <%= render "left_menu" %>
  </div>
  <!-- .row -->
</div>